version: "3.8"

services:
  lilith:
    build:
      context: .
      dockerfile: Lilith/Dockerfile
    ports:
      - "5241:5241"
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5241
    # networks:
      # - app-network

# networks:
#   app-network:
#     driver: bridge

